name: Build Android APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Initialize Buildozer if needed
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Install Android SDK Command-line tools manually
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          cd ~/.buildozer/android/platform/android-sdk/cmdline-tools
          curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip tools.zip
          mv cmdline-tools latest
        shell: bash

      - name: Accept licenses and install platform tools
        env:
          ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"
        shell: bash

      - name: Build APK
        run: buildozer android release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: bin/*.apk
