name: Android Release Build

on:
  push:
    tags:
      - 'v*' # 例如 v1.0.0 推 tag 才會觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup Android SDK
      env:
        ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
      run: |
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
        cd "$ANDROID_SDK_ROOT/cmdline-tools"
        curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q cmdline-tools.zip
        rm cmdline-tools.zip
        mkdir -p latest
        mv cmdline-tools/* latest/
        chmod +x latest/bin/*
        yes | latest/bin/sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses
        latest/bin/sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;31.0.0" \
          "ndk;25.1.8937393"

    - name: Link sdkmanager legacy path
      run: |
        mkdir -p "$ANDROID_SDK_ROOT/tools"
        ln -s "$ANDROID_SDK_ROOT/cmdline-tools/latest" "$ANDROID_SDK_ROOT/tools/bin"

    - name: Install Python dependencies
      run: |
        pip install buildozer
        pip install cython==0.29.33

    - name: Decode keystore file
      run: |
        echo "$KEYSTORE_BASE64" | base64 -d > my-release-key.keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

    - name: Build Release APK
      env:
        ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
        ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
        PATH: ${{ env.PATH }}:/home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
      run: |
        export ANDROIDSDK=$ANDROID_SDK_ROOT
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        buildozer android release

    - name: Upload Release to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
