name: Build Android APK

on:
  push:
    tags:
      - 'v*'  # 自動觸發版本號，例如 v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Create buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: 修復 Buildozer 相容的 sdkmanager 路徑
        run: |
          mkdir -p $ANDROID_SDK_ROOT/tools
          ln -sf $ANDROID_SDK_ROOT/cmdline-tools/latest $ANDROID_SDK_ROOT/tools/

      - name: Build Release APK
        env:
          ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
          ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
        run: |
          export ANDROIDSDK=$ANDROID_SDK_ROOT
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          buildozer android release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: bin/*.apk
